// RTL include list — compile this single file to pull in all RTL modules
`include "uart_tx_fifo.v"
`include "uart_tx_clk_gen.v"
`include "uart_tx_fsm.v"
`include "uart_tx_top.v"
`include "uart_rx_fifo.v"
`include "uart_rx_clk_gen.v"
`include "uart_rx_bit_sampler.v"
`include "uart_rx_negedge_detect.v"
`include "uart_rx_fsm.v"
`include "uart_rx_top.v"
`include "uart_top.v"
`include "apb_slave.sv"
`include "apb2uart_top.sv"
