
// This file was autogenerated by PeakRDL-uvm
package uart_regs_uvm_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - uart_regs::CONFIG0
    class uart_regs__CONFIG0 extends uvm_reg;
        rand uvm_reg_field parity_en;
        rand uvm_reg_field uart_sm;
        rand uvm_reg_field uart_tx_en;
        rand uvm_reg_field uart_rx_en;

        function new(string name = "uart_regs__CONFIG0");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.parity_en = new("parity_en");
            this.parity_en.configure(this, 1, 0, "RW", 0, 'h0, 0, 1, 0);
            this.uart_sm = new("uart_sm");
            this.uart_sm.configure(this, 5, 1, "RW", 0, 'h0, 0, 1, 0);
            this.uart_tx_en = new("uart_tx_en");
            this.uart_tx_en.configure(this, 1, 6, "RW", 0, 'h0, 0, 1, 0);
            this.uart_rx_en = new("uart_rx_en");
            this.uart_rx_en.configure(this, 1, 7, "RW", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : uart_regs__CONFIG0

    // reg - uart_regs::CONFIG1
    class uart_regs__CONFIG1 extends uvm_reg;
        rand uvm_reg_field stop_bit_count;
        rand uvm_reg_field packet_width;
        rand uvm_reg_field parity_odd_even;
        rand uvm_reg_field reserved;

        function new(string name = "uart_regs__CONFIG1");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.stop_bit_count = new("stop_bit_count");
            this.stop_bit_count.configure(this, 2, 0, "RW", 0, 'h0, 0, 1, 0);
            this.packet_width = new("packet_width");
            this.packet_width.configure(this, 2, 2, "RW", 0, 'h0, 0, 1, 0);
            this.parity_odd_even = new("parity_odd_even");
            this.parity_odd_even.configure(this, 1, 4, "RW", 0, 'h0, 0, 1, 0);
            this.reserved = new("reserved");
            this.reserved.configure(this, 3, 5, "RW", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : uart_regs__CONFIG1

    // reg - uart_regs::STATUS0
    class uart_regs__STATUS0 extends uvm_reg;
        rand uvm_reg_field rx_fifo_read_error;
        rand uvm_reg_field rx_fifo_write_error;
        rand uvm_reg_field tx_fifo_write_error;
        rand uvm_reg_field rx_frame_error;
        rand uvm_reg_field rx_parity_error;
        rand uvm_reg_field reserved0;

        function new(string name = "uart_regs__STATUS0");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.rx_fifo_read_error = new("rx_fifo_read_error");
            this.rx_fifo_read_error.configure(this, 1, 0, "RO", 1, 'h0, 0, 1, 0);
            this.rx_fifo_write_error = new("rx_fifo_write_error");
            this.rx_fifo_write_error.configure(this, 1, 1, "RO", 1, 'h0, 0, 1, 0);
            this.tx_fifo_write_error = new("tx_fifo_write_error");
            this.tx_fifo_write_error.configure(this, 1, 2, "RO", 1, 'h0, 0, 1, 0);
            this.rx_frame_error = new("rx_frame_error");
            this.rx_frame_error.configure(this, 1, 3, "RO", 1, 'h0, 0, 1, 0);
            this.rx_parity_error = new("rx_parity_error");
            this.rx_parity_error.configure(this, 1, 4, "RO", 1, 'h0, 0, 1, 0);
            this.reserved0 = new("reserved0");
            this.reserved0.configure(this, 3, 5, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : uart_regs__STATUS0

    // reg - uart_regs::STATUS1
    class uart_regs__STATUS1 extends uvm_reg;
        rand uvm_reg_field rx_fifo_empty;
        rand uvm_reg_field rx_fifo_full;
        rand uvm_reg_field tx_fifo_full;
        rand uvm_reg_field reserved1;

        function new(string name = "uart_regs__STATUS1");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.rx_fifo_empty = new("rx_fifo_empty");
            this.rx_fifo_empty.configure(this, 1, 0, "RO", 1, 'h0, 0, 1, 0);
            this.rx_fifo_full = new("rx_fifo_full");
            this.rx_fifo_full.configure(this, 1, 1, "RO", 1, 'h0, 0, 1, 0);
            this.tx_fifo_full = new("tx_fifo_full");
            this.tx_fifo_full.configure(this, 1, 2, "RO", 1, 'h0, 0, 1, 0);
            this.reserved1 = new("reserved1");
            this.reserved1.configure(this, 5, 3, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : uart_regs__STATUS1

    // addrmap - uart_regs
    class uart_regs extends uvm_reg_block;
        rand uart_regs__CONFIG0 config0;
        rand uart_regs__CONFIG1 config1;
        rand uart_regs__STATUS0 status0;
        rand uart_regs__STATUS1 status1;

        function new(string name = "uart_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 1, UVM_NO_ENDIAN);
            this.config0 = new("config0");
            this.config0.configure(this);

            this.config0.build();
            this.default_map.add_reg(this.config0, 'h0);
            this.config1 = new("config1");
            this.config1.configure(this);

            this.config1.build();
            this.default_map.add_reg(this.config1, 'h1);
            this.status0 = new("status0");
            this.status0.configure(this);

            this.status0.build();
            this.default_map.add_reg(this.status0, 'h2);
            this.status1 = new("status1");
            this.status1.configure(this);

            this.status1.build();
            this.default_map.add_reg(this.status1, 'h3);
        endfunction : build
    endclass : uart_regs

endpackage: uart_regs_uvm_pkg
